/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package haarfilterall.features;

import haarfilterall.util.CalculateFeature;

/**
 *
 * @author user
 */
public class Features {

    /**
     * Two layer Horizontal Sliding Window
     */
    public int[] FeatureA(int w, int h, int[][] intValues) {
        int imgH = 24;
        int imgW = 24;
        int count = 0;
        int tempFeature = 0;
        int[] featureValues = new int[43200];
//        int[][] integralValues = new int[5][5];
        /**
         * Image area is a class to calculate the area of a certain window
         * generated by the i and j values in the following loop and sliding it
         * through each position of the array which will later be replaced by an
         * image to calculate its features
         */
        CalculateFeature calculateFeature = new CalculateFeature();

        for (int i = 1; i <= (imgW / w); i++) {
            for (int j = 1; j <= (imgH / h); j++) {
                for (int x = 1; x <= (imgW - i * w + 1); x++) {
                    for (int y = 1; y <= imgH - j * h + 1; y++) {
                        /**
                         * CalculateArea gives the area of the selected window
                         * with reference to the integral image and drastically
                         * reduces the computation time
                         */
                        if (x != 1 && y != 1) {

                            tempFeature = calculateFeature.CalculateSubtractionA(i, j, x, y, count, intValues);
                            count++;
                            featureValues[count] = tempFeature;

                        }
                    }
                }
            }
        }
        return featureValues;
    }

    /**
     * Rest of the program follows exactly the same pattern as the above
     * function. Different functions created to reduce the time taken by
     * IF..ELSE statements. Direct calls to the function
     */
    /**
     * Three layer Vertical Sliding Window
     */
    public int[] FeatureB(int w, int h, int[][] intValues) {
        int imgH = 24;
        int imgW = 24;
        int count = 0;
        int tempFeature = 0;
        int[] featureValues = new int[43200];
//        int[][] integralValues = new int[5][5];

        CalculateFeature calculateFeature = new CalculateFeature();

        for (int i = 1; i <= (imgH / h); i++) {
            for (int j = 1; j <= (imgW / w); j++) {
                for (int x = 1; x <= (imgH - i * h + 1); x++) {
                    for (int y = 1; y <= imgW - j * w + 1; y++) {
                        if (x != 1 && y != 1) {
                            tempFeature = calculateFeature.CalculateSubtractionB(j, i, y, x, count, intValues);
                            count++;
                            featureValues[count] = tempFeature;
                        }
                    }
                }
            }
        }
        return featureValues;
    }

    /**
     * Three layer Horizontal Sliding Window
     */
    public int[] FeatureC(int w, int h, int[][] intValues) {
        int imgH = 24;
        int imgW = 24;
        int count = 0;
        int tempFeature = 0;
        int[] featureValues = new int[27600];
//        int[][] integralValues = new int[5][5];

        CalculateFeature calculateFeature = new CalculateFeature();

        for (int i = 1; i <= (imgW / w); i++) {
            for (int j = 1; j <= (imgH / h); j++) {
                for (int x = 1; x <= (imgW - i * w + 1); x++) {
                    for (int y = 1; y <= imgH - j * h + 1; y++) {
                        if (x != 1 && y != 1) {
                            tempFeature = calculateFeature.CalculateSubtractionC(i, j, x, y, count, intValues);
                            count++;
                            featureValues[count] = tempFeature;
                        }
                    }
                }
            }
        }
        return featureValues;
    }

    /**
     * Four layer Rectangular Sliding Window
     */
    public int[] FeatureE(int w, int h, int[][] intValues) {
        int imgH = 24;
        int imgW = 24;
        int count = 0;
        int tempFeature = 0;
        int[] featureValues = new int[43200];
//        int[][] integralValues = new int[5][5];

        CalculateFeature calculateFeature = new CalculateFeature();

        for (int i = 1; i <= (imgW / w); i++) {
            for (int j = 1; j <= (imgH / h); j++) {
                for (int x = 1; x <= (imgW - i * w + 1); x++) {
                    for (int y = 1; y <= imgH - j * h + 1; y++) {

                        if (x != 1 && y != 1) {
                            tempFeature = calculateFeature.CalculateSubtractionE(i, j, x, y, count, intValues);
                            count++;
                            featureValues[count] = tempFeature;
                        }
                    }
                }
            }
        }
        return featureValues;
    }
}
